name: Test (Setup Java)
run-name: Whatever? I'm learning alright
on:
    - push
    - pull_request

jobs:
    mvn:
        strategy:
            matrix:
                version: 
                    - 17
                    - 19
                    - 20
                distribution:
                    - corretto
                    - temurin
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
            distribution: ${{ matrix.distribution}}
            java-version: ${{ matrix.version }}
            cache: 'maven'
        - uses: eric2788/maven-jar-publish@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - run: mkdir staging
        - uses: KnicKnic/os-specific-run@v1.0.4
          with:
            linux: cp target/*.jar staging
            windows: copy target/*.jar staging
        - uses: actions/upload-artifact@v3
          with:
            name: Package
            path: staging
        - name: Build with Maven
          run: mvn -B package --file pom.xml
